#!/usr/bin/perl
use v5.18;

my $power_folder = '/sys/devices/LNXSYSTM:00/device:00/PNP0C0A:00/power_supply/BAT0/';
my $power_now_file = $power_folder . 'power_now';
my $energy_full_file = $power_folder . 'energy_full';
my $energy_now_file = $power_folder . 'energy_now';

open(my $power, '<', $power_now_file);
chomp(my $power_now = <$power>);

open($power, '<', $energy_full_file);
chomp(my $energy_full = <$power>);

open($power, '<', $energy_now_file);
chomp(my $energy_now = <$power>);

my $energy_percent = $energy_now * 100 / $energy_full;

printf "%.1fW ", $power_now / 1000000;
printf "%.1f%\n", $energy_percent;

close($power);
