#!/usr/bin/perl
#Reads energy and power information from the battery and prints current power
#being used and battery percentage.
#I use it for my Tmux statusbar
use v5.18;

my $power_folder = '/sys/devices/LNXSYSTM:00/device:00/PNP0C0A:00/power_supply/BAT0/';
my $power_now_file = $power_folder . 'power_now';
my $energy_full_file = $power_folder . 'energy_full';
my $energy_now_file = $power_folder . 'energy_now';

open(my $power, '<', $power_now_file);
chomp(my $power_now = <$power>);

open($power, '<', $energy_full_file);
chomp(my $energy_full = <$power>);

open($power, '<', $energy_now_file);
chomp(my $energy_now = <$power>);

my $energy_percent;
if ($energy_full > 0) {
	$energy_percent = $energy_now * 100 / $energy_full;
} else {
	die "Oops, are you sure there's a battery in this computer?\n";
}

if($power_now) {
	printf "%.1fW ", $power_now / 1000000;
} else {
	if( $energy_percent < 100 ) {
		print "Charging ";
	} else {
		print "Charged ";
	}
}
printf "%.1f%\n", $energy_percent;

close($power);
