#!/usr/bin/env perl

use strict;
use utf8;

if ($#ARGV < 0) {
	die "\n Uso: envio_correos <numeros de seguimiento>\n";
}

foreach my $numero (0 .. $#ARGV) {
	open(DATA,'-|', "curl -s --data 'accion=LocalizaUno&numero=$ARGV[$numero]&ecorreo=&numeros=' 'aplicacionesweb.correos.es/localizadorenvios/track.asp'") or die "No se ha podido establecer la conexión\n";

	my $datos;

	foreach (<DATA>) {
		if($_ =~ m/<Evento>/) {
			$datos = $_;
		}
	}
	close(DATA);

	print "\nNumero: $ARGV[$numero]\n";
	while($datos =~ m|<Fecha>((?:\d+/?){2})/\d{4}</Fecha><Hora>((?:\d+:?){2}):\d\d</Hora>.*?<Evento>(.*?)</Evento>.*?<DescripcionWeb>(.*?)</DescripcionWeb>|g) {
		printf "%-8s %-8s %-40s %-40s\n", $1, $2, $3, $4;
	}

}
