#!/usr/bin/env perl

use v5.18;
use utf8;

if ($#ARGV < 0) {
	die "\n Uso: envio_correos <numeros de seguimiento>\n";
}

foreach my $numero (0 .. $#ARGV) {
	open(DATA,'-|', "curl -s --data 'accion=LocalizaUno&numero=$ARGV[$numero]&ecorreo=&numeros=' 'aplicacionesweb.correos.es/localizadorenvios/track.asp'") or die "No se ha podido establecer la conexión\n";

	my $datos;

	foreach (<DATA>) {
		if($_ =~ m/<Evento>/) {
			$datos = $_;
		}
	}
	close(DATA);

	print "\nNumero: $ARGV[$numero]\n";
	while($datos =~ m|<Fecha>((?:\d+/?)+)</Fecha><Hora>((?:\d+:?)+)</Hora>.*?<Evento>(.*?)</Evento>.*?<DescripcionWeb>(.*?)</DescripcionWeb>|g) {
		print "\t$1\t$2\t$3\t---\t$4\n"
	}

}
