#!/usr/bin/perl
# This script gathers wireless information from the output of iw and prints
# what you want.
# I use it for my Tmux statusbar
use v5.18;

my $interface = 'wlp2s0';
open(my $iw_output, '-|', "iw $interface link");

my %params;
while (my $line = <$iw_output>) {
	if($line =~ m/^Connected\ to\ ((\w\w:){5}\w\w)\ \(on\ wlp2s0\)/) {
		chomp($params{'AP'} = $1);
		next;
	}
	$line =~ m/^(\s+)?(\w+(\s\w+)?):\s+([-0-9a-zA-Z]+(\.\d+)?(\s\w+(\/\w)?)?)$/;
	chomp($params{$2} = $4);
}
close($iw_output);

if($params{'SSID'} && $params{'signal'}) {
	say "$params{'SSID'} $params{'signal'}";
} else {
	say "Disconnected";
}
